### ISSUE TITLE
Need help in testing LPW in WINDOWS machine

### ISSUE THREAD

**Issue by kspviswa** [kspviswa/local-packet-whisperer#3]
Although I took care to ensure that LPW is cross platform, I couldn't be sure since I don't own a windows machine to test LPW.
I'm looking for some community support to test and validate lpw in windows and open issue if you find any gaps.

**Comment by madhusowmya** [comment]
unable to install lpw  on mac

**Comment by kspviswa** [comment]
Hi, can you please elaborate? This ticket is to help test lpw on windows host. Are you saying you are unable to do pip install lpw on Mac host? If so what error are you getting ?

**Comment by madhusowmya** [comment]
Could not fetch URL https://pypi.org/simple/lpw/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/lpw/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1129)'))) - skipping
ERROR: Could not find a version that satisfies the requirement lpw (from versions: none)
ERROR: No matching distribution found for lpw

**Comment by kspviswa** [comment]
Looks like you are having issues connecting to pypi.org . Are you behind corporate firewall or vpn ?

**Comment by kspviswa** [comment]
Hi I retested on my machine and it works as usual. Please ensure you have python 3.12+ and a connection to pypi.org. Or you can try cloning the repo and install the `requirements.txt` yourself. I'll soon be publishing a brew formula as well. Stay tuned.

**Comment by madhusowmya** [comment]
Other than dolphin-mistral:latest can I replace that with mistral v0.2

**Comment by jprall32** [comment]
I am unable to get lpw working on windows.  The streamlit internal web server never launches and there are no error messages to provide any detail as to why it didn't launch.  I think it has to do with %PATH% issues and/or assumptions made with the lpw.py script about directory structure when under windows.  for example, when pip installed, it installs to: C:\Users\jpral\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\lpw.py.  Seems like an odd place, but that's where it physically resides on my computer.  It would be nice if you added debug statements in your code to help trace down problems when starting the application.  

I'm happy to iterate with you on a fix, but I might be able to get a VM available for you to use for your own testing....

**Comment by jprall32** [comment]
Ok, after much mucking around, I was able to get it to work.  I needed to remove the python from the MS store.  It appends unique app IDs to the directory names making it a pain to work with.  I then installed python 3.13 and the install script failed miserably with that.  Then I handbuillt 3.11 and then did a bunch of %PATH% work.   So that's the good news.  Basically windows stank on the python install and then path mgmt.  ChatGPT was a godsend in helping me clean all this stuff up.

One primary problem I'm having is the performance is increeedibly slow.  I got this working on a Fedora 39 VM on the same computer and while it was slow (no access to the GPU), the direct in windows version is waaaaaaay slower than that.  for a 35MB pcapng file, it takes 3 minutes to 'crunch the packets'.  And then it goes into processing for many more minutes.  When I run ollama run dolphin-mistral:latest it is very peppy.  I have a 4090.  But I don't know what is happening that it is so slow when invoked by lpw.  Do you need to pass flags to use the GPU?

**Comment by kspviswa** [comment]
lpw basically access the ollama REST API server that's it. It doesn't change anything at ollama level. Hence both ollama run command and lpw are effectively using the same endpoint. Is lpw running natively in windows or inside a VM?

**Comment by jprall32** [comment]
All of my work today has been to get it running natively in windows.  No VMs.  I could see how maybe crunching packets can take a minute (not 3) but when it goes into processing to actually answer, it takes 10 mins for example.  I don't remotely know how to debug this one...  Tell me any information you want from me
